[[User-API]]
== User API
+
[[User-모두-조회]]
=== User 모두 조회
operation::user-controller-test/all_users_get[snippets='http-request,http-response,response-fields']

[[User-단일-조회]]
=== User 단일 조회
operation::user-controller-test/user_get[snippets='http-request,path-parameters,http-response,response-fields']
+
[[User-아이디-단일-조회]]
=== User 아이디 단일 조회
operation::user-controller-test/user_by-user-id_get[snippets='http-request,path-parameters,http-response,response-fields']

[[User-이메일-단일-조회]]
=== User 이메일 단일 조회
operation::user-controller-test/user_by-email_get[snippets='http-request,path-parameters,http-response,response-fields']

[[User-로그인-사용자-단일-조회]]
=== User 로그인 사용자 단일 조회
operation::user-controller-test/user_current_get[snippets='http-request,response-fields,http-response']
+
[[User-생성]]
=== User 생성
operation::user-controller-test/user_post[snippets='http-request,response-fields,http-response']

[[User-로그인-성공]]
=== User 로그인 성공
operation::user-controller-test/user_success_login[snippets='http-request,response-fields,http-response']

[[User-로그인-실패]]
=== User 로그인 실패
operation::user-controller-test/user_fail_login[snippets='http-request,http-response']